// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID         int64
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
	FirstName  string
	LastName   string
	Email      string
	PictureUrl string
}
