#!/usr/bin/env bash

set -e # Exit on failure

# Setup on_the_shelf_dev_db database
passwd=$( date | md5 )
psql postgres -c "create role on_the_shelf_dev_db_user superuser createdb login;"
createdb -O "on_the_shelf_dev_db_user" on_the_shelf_dev_db
psql postgres -c "grant all on database on_the_shelf_dev_db to $( whoami );"
